spring.datasource.url=jdbc:h2:mem:testdb

spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always

# JPA / Hibernate
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

spring.security.user.name=admin
spring.security.user.password=admin123

#Configurado para usar variável de ambiente OU senha padrão, caso a primeira não exista
api.security.token.secret=101111213
#api.security.token.secret=${JWT_SECRET:101111213}